[package]
name = "triangles"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.30"
vulkano-shaders = "0.30"
vulkano-win = "0.30"
nalgebra = "0.31"
winit = "0.26"

bytemuck = "1.12"
image = "0.24"
